USE [GEDMAF]
GO

DECLARE @ID_DOC_DUPLICATED AS VARCHAR(32) = '2024021200000300000445'
DECLARE @NEW_ID_DOC VARCHAR(32) =           '2024021200000300000446'
DECLARE @IS_NEW_ID_DOC_AVAILABLE AS BIT = IIF((SELECT COUNT([DOCN]) FROM [dbo].[ARCHEAMAF] WHERE [ID_DOC] = @NEW_ID_DOC) = 0, 1, 0)
DECLARE @ERROR_MESSAGE AS NVARCHAR(100)

IF @IS_NEW_ID_DOC_AVAILABLE = 0
BEGIN
	SET @ERROR_MESSAGE = CONCAT('L''identifiant ', @NEW_ID_DOC, ' est déjà utilisé');
	THROW 51000, @ERROR_MESSAGE, 1;
END

SELECT [DOCN]
INTO #DOCN_OF_DOCUMENT_DUPLICATE
FROM [dbo].[ARCHEAMAF]
WHERE [ID_DOC] = @ID_DOC_DUPLICATED
AND [DATE_NUM] = 20240212
AND [HEURE_NUM] = 120817
AND [GESTIONNAIRE_REDAC] IS NULL
AND [COTE] IS NULL
AND [PRIORITE] = 2
AND [DOC_SIZE] IS NULL

DECLARE @IS_TARGET_DOCUMENT_DUPLICATE_UNIQUE AS BIT = IIF((SELECT COUNT(*) FROM #DOCN_OF_DOCUMENT_DUPLICATE) = 1, 1, 0)
IF @IS_TARGET_DOCUMENT_DUPLICATE_UNIQUE = 0
BEGIN
	SELECT * FROM #DOCN_OF_DOCUMENT_DUPLICATE
	DROP TABLE #DOCN_OF_DOCUMENT_DUPLICATE
	SET @ERROR_MESSAGE = 'Le document doublon ciblé par la suppression est équivoque';
	THROW 51000, @ERROR_MESSAGE, 1;
END

DECLARE @DOCN_OF_DOCUMENT_TO_DELETE AS VARCHAR(9) = (SELECT TOP 1 [DOCN] FROM #DOCN_OF_DOCUMENT_DUPLICATE)
UPDATE [dbo].[ARCHEAMAF]
SET [STATUS_INDEXATION] = 'SUPPRIME',
    [ID_DOC] = @NEW_ID_DOC
WHERE [DOCN] = @DOCN_OF_DOCUMENT_TO_DELETE

DROP TABLE #DOCN_OF_DOCUMENT_DUPLICATE

GO
